// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/jp/docs/server-tab": {
    params: {};
  };
  "/jp/docs/model-tab": {
    params: {};
  };
  "/jp/docs/chat-tab": {
    params: {};
  };
  "/jp/docs/settings": {
    params: {};
  };
  "/jp/privacy-policy": {
    params: {};
  };
  "/jp/release-notes": {
    params: {};
  };
  "/docs/server-tab": {
    params: {};
  };
  "/docs/model-tab": {
    params: {};
  };
  "/docs/chat-tab": {
    params: {};
  };
  "/docs/settings": {
    params: {};
  };
  "/privacy-policy": {
    params: {};
  };
  "/release-notes": {
    params: {};
  };
  "/jp/support": {
    params: {};
  };
  "/sitemap.xml": {
    params: {};
  };
  "/jp/docs": {
    params: {};
  };
  "/support": {
    params: {};
  };
  "/docs": {
    params: {};
  };
  "/robots.txt": {
    params: {};
  };
  "/jp": {
    params: {};
  };
  "/_image/*": {
    params: {
      "*": string;
    };
  };
  "/jp/*": {
    params: {
      "*": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/jp/docs/server-tab" | "/jp/docs/model-tab" | "/jp/docs/chat-tab" | "/jp/docs/settings" | "/jp/privacy-policy" | "/jp/release-notes" | "/docs/server-tab" | "/docs/model-tab" | "/docs/chat-tab" | "/docs/settings" | "/privacy-policy" | "/release-notes" | "/jp/support" | "/sitemap.xml" | "/jp/docs" | "/support" | "/docs" | "/robots.txt" | "/jp" | "/_image/*" | "/jp/*" | "/*";
  };
  "routes/[jp].[docs].[server-tab]._index.tsx": {
    id: "routes/[jp].[docs].[server-tab]._index";
    page: "/jp/docs/server-tab";
  };
  "routes/[jp].[docs].[model-tab]._index.tsx": {
    id: "routes/[jp].[docs].[model-tab]._index";
    page: "/jp/docs/model-tab";
  };
  "routes/[jp].[docs].[chat-tab]._index.tsx": {
    id: "routes/[jp].[docs].[chat-tab]._index";
    page: "/jp/docs/chat-tab";
  };
  "routes/[jp].[docs].[settings]._index.tsx": {
    id: "routes/[jp].[docs].[settings]._index";
    page: "/jp/docs/settings";
  };
  "routes/[jp].[privacy-policy]._index.tsx": {
    id: "routes/[jp].[privacy-policy]._index";
    page: "/jp/privacy-policy";
  };
  "routes/[jp].[release-notes]._index.tsx": {
    id: "routes/[jp].[release-notes]._index";
    page: "/jp/release-notes";
  };
  "routes/[docs].[server-tab]._index.tsx": {
    id: "routes/[docs].[server-tab]._index";
    page: "/docs/server-tab";
  };
  "routes/[docs].[model-tab]._index.tsx": {
    id: "routes/[docs].[model-tab]._index";
    page: "/docs/model-tab";
  };
  "routes/[docs].[chat-tab]._index.tsx": {
    id: "routes/[docs].[chat-tab]._index";
    page: "/docs/chat-tab";
  };
  "routes/[docs].[settings]._index.tsx": {
    id: "routes/[docs].[settings]._index";
    page: "/docs/settings";
  };
  "routes/[privacy-policy]._index.tsx": {
    id: "routes/[privacy-policy]._index";
    page: "/privacy-policy";
  };
  "routes/[release-notes]._index.tsx": {
    id: "routes/[release-notes]._index";
    page: "/release-notes";
  };
  "routes/[jp].[support]._index.tsx": {
    id: "routes/[jp].[support]._index";
    page: "/jp/support";
  };
  "routes/[sitemap.xml]._index.tsx": {
    id: "routes/[sitemap.xml]._index";
    page: "/sitemap.xml";
  };
  "routes/[jp].[docs]._index.tsx": {
    id: "routes/[jp].[docs]._index";
    page: "/jp/docs";
  };
  "routes/[support]._index.tsx": {
    id: "routes/[support]._index";
    page: "/support";
  };
  "routes/[docs]._index.tsx": {
    id: "routes/[docs]._index";
    page: "/docs";
  };
  "routes/[robots.txt].tsx": {
    id: "routes/[robots.txt]";
    page: "/robots.txt";
  };
  "routes/[jp]._index.tsx": {
    id: "routes/[jp]._index";
    page: "/jp";
  };
  "routes/[_image].$.ts": {
    id: "routes/[_image].$";
    page: "/_image/*";
  };
  "routes/[jp].$.tsx": {
    id: "routes/[jp].$";
    page: "/jp/*";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/[jp].[docs].[server-tab]._index": typeof import("./app/routes/[jp].[docs].[server-tab]._index.tsx");
  "routes/[jp].[docs].[model-tab]._index": typeof import("./app/routes/[jp].[docs].[model-tab]._index.tsx");
  "routes/[jp].[docs].[chat-tab]._index": typeof import("./app/routes/[jp].[docs].[chat-tab]._index.tsx");
  "routes/[jp].[docs].[settings]._index": typeof import("./app/routes/[jp].[docs].[settings]._index.tsx");
  "routes/[jp].[privacy-policy]._index": typeof import("./app/routes/[jp].[privacy-policy]._index.tsx");
  "routes/[jp].[release-notes]._index": typeof import("./app/routes/[jp].[release-notes]._index.tsx");
  "routes/[docs].[server-tab]._index": typeof import("./app/routes/[docs].[server-tab]._index.tsx");
  "routes/[docs].[model-tab]._index": typeof import("./app/routes/[docs].[model-tab]._index.tsx");
  "routes/[docs].[chat-tab]._index": typeof import("./app/routes/[docs].[chat-tab]._index.tsx");
  "routes/[docs].[settings]._index": typeof import("./app/routes/[docs].[settings]._index.tsx");
  "routes/[privacy-policy]._index": typeof import("./app/routes/[privacy-policy]._index.tsx");
  "routes/[release-notes]._index": typeof import("./app/routes/[release-notes]._index.tsx");
  "routes/[jp].[support]._index": typeof import("./app/routes/[jp].[support]._index.tsx");
  "routes/[sitemap.xml]._index": typeof import("./app/routes/[sitemap.xml]._index.tsx");
  "routes/[jp].[docs]._index": typeof import("./app/routes/[jp].[docs]._index.tsx");
  "routes/[support]._index": typeof import("./app/routes/[support]._index.tsx");
  "routes/[docs]._index": typeof import("./app/routes/[docs]._index.tsx");
  "routes/[robots.txt]": typeof import("./app/routes/[robots.txt].tsx");
  "routes/[jp]._index": typeof import("./app/routes/[jp]._index.tsx");
  "routes/[_image].$": typeof import("./app/routes/[_image].$.ts");
  "routes/[jp].$": typeof import("./app/routes/[jp].$.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/$": typeof import("./app/routes/$.tsx");
};